import { CartCounter } from "@/app/shopping-cart/components/CartCounter";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Counter Page",
  description: "Generated by create me",
};

export default function CounterPage() {
  return (
    <div className="flex flex-col items-center justify-center w-full h-full">
      <h1>Counter Page</h1>
      <CartCounter value={10} />
    </div>
  );
}
